#!/usr/bin/env bash
# catalog-index.sh — keep the Backstage catalog index for the test-env XR
# claims in sync.
#
# This repo does NOT use Backstage GitHub discovery, and the XR claims here are
# test-env only, so the catalog surface is deliberately scoped to the tests/
# subtree (this script lives at tests/.backstage/ and treats tests/ as its
# root). The catalog is driven by an explicit `kind: Location` index
# (tests/.backstage/catalog-locations.yaml). Location targets do not support
# globs, so the index must list every catalog-info.yaml by hand — this script
# regenerates it deterministically so nobody has to.
#
# Unlike the harvester repo's variant there is no provenance `stamp` step: the
# claim catalog-info.yaml files are written by claim-machinery and already carry
# their own backstage.io/source-location, so there is nothing to back-fill.
#
# Command:
#   index   (default) regenerate tests/.backstage/catalog-locations.yaml from
#           every catalog-info.yaml under tests/. Self-heals on adds AND deletes.
#
# Idempotent: re-running with no underlying change produces no diff, so a CI
# commit loop terminates on its own.
set -euo pipefail

# Script lives at tests/.backstage/ — its parent (tests/) is the scan root, and
# all index targets resolve relative to this file's own directory.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

INDEX_FILE=".backstage/catalog-locations.yaml"
LOCATION_NAME="crossplane-configurations-xrs"
LOCATION_DESC="Test-env Crossplane XR claims (harvester/crossplane-mgmt)"

# Find every catalog-info.yaml under tests/ (paths relative to ROOT). Exclude
# .git defensively; nothing else vendored here ships catalog-info.yaml.
find_catalog_files() {
  find . -type f -name 'catalog-info.yaml' \
    -not -path '*/.git/*' 2>/dev/null \
    | sed 's|^\./||' | LC_ALL=C sort
}

log() { printf '  %s\n' "$*" >&2; }

gen_index() {
  log "scanning tests/ for catalog-info.yaml …"
  mapfile -t files < <(find_catalog_files)

  if [ "${#files[@]}" -eq 0 ]; then
    log "no catalog-info.yaml found — refusing to write an empty index"
    return 1
  fi

  {
    echo "apiVersion: backstage.io/v1alpha1"
    echo "kind: Location"
    echo "metadata:"
    echo "  name: ${LOCATION_NAME}"
    echo "  description: ${LOCATION_DESC}"
    echo "  # GENERATED by tests/.backstage/catalog-index.sh — do not edit by hand."
    echo "spec:"
    echo "  targets:"
    for f in "${files[@]}"; do
      # ../ climbs from tests/.backstage/ back to tests/, where the scan ran.
      echo "    - ../${f}"
    done
  } > "${INDEX_FILE}.tmp"

  if [ -f "$INDEX_FILE" ] && diff -q "$INDEX_FILE" "${INDEX_FILE}.tmp" >/dev/null; then
    rm -f "${INDEX_FILE}.tmp"
    log "index unchanged (${#files[@]} targets)"
  else
    mv "${INDEX_FILE}.tmp" "$INDEX_FILE"
    log "index regenerated (${#files[@]} targets)"
  fi
}

case "${1:-index}" in
  index) gen_index ;;
  *) echo "usage: $0 [index]" >&2; exit 2 ;;
esac
